version: "3"
services:

  glpi:
    image: glpi:0.0.2
    ports:
      - 8080:80
    depends_on: 
      - db
    networks:
      - glpi

  db:
    image: mariadb:10
    env_file: .env
    volumes:
      - $PWD/mariadb/data:/var/lib/mysql
    networks:
      - glpi

networks: 
  glpi:
