version: "3"
services:

  glpi:
    image: glpi:0.0.4
    ports:
      - 8080:80
    volumes:
      - ./glpi/config:/var/www/html/config
      - ./glpi/log:/var/www/html/files/_log
    depends_on:
      - db
    networks:
      - glpi

  db:
    image: mariadb:10
    env_file: .env
    volumes:
      - ./mariadb/data:/var/lib/mysql
    networks:
      - glpi

networks:
  glpi:
